name: cmap_visualization_toolkit
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<3.13.2
  - numpy>=1.24,<2.2
  - pandas>=1.5,<2.3
  - nltk>=3.8,<4
  - gensim>=4.3,<5
  - scikit-learn>=1.2,<1.5
  - scipy
  - matplotlib>=3.7,<4
  - seaborn>=0.12,<1
  - networkx>=3,<4
  - plotly>=5.0,<6
  - dash>=2.10,<3
  - joblib>=1.2,<2
  - tqdm>=4.65,<5
  - packaging>=20.0
  - pip>=22.0.0
  - pip:
    - sentence-transformers>=2.2,<3.6
    - transformers>=4.36,<5.1
    - torch>=2.1,<2.8
    - wordcloud>=1.9,<2
    - dill>=0.3.6,<0.4
    - python-dotenv>=0.15,<2
    - pydantic>=1.10,<3
